### ISSUE TITLE
CMakeLists.txt patch for Windows (CLion etc.)

### ISSUE THREAD

**Issue by hamish-milne** [HPCE/hpce-2017-cw3#10]
Adding this as an issue instead of a pull request because I'm lazy.

```
@@ -93,8 +93,11 @@ endforeach(SRC_FILE ${USR_SRC})
 ##
 ## ==============================================================================

-set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-Wall -std=c++11 -o2")
+set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-Wall -std=gnu++11 -o2")

+## Get rid of DLL errors
+set(BUILD_SHARED_LIBS OFF)
+set(CMAKE_EXE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS} "-static")

 ## ==============================================================================
 ##
```

I think the only case where this would cause a problem is where a compiler doesn't like `-std=gnu++11`, and GCC, MinGW, and I believe clang all support this.

If using CLion, you'll probably want to set the output directory to something sensible, by changing File > Settings > Build... > CMake > Build output path. Then you can see your executables!

**Comment by m8pple** [comment]
Ok, I'll patch this without really knowing what it is changing :)

What is the issue with gnu++11 vs c++11? I missed that.

**Comment by hamish-milne** [comment]
`-std=gnu++11` fixed a lot of errors related to how the compiler handled included headers; as in it didn't originally like the GNU-specific syntax in there. I'm not sure why this happens here and not anywhere else, but I guess it's something specific to the combination of MinGW, Windows and CMake.

The `-static` flag bundles all the libraries with the executable, like the MinGW libstdc++ and such. I found that while running it from the IDE worked fine, running it from the command line (which we need to do a lot for this CW) meant it couldn't find all the necessary DLLs, so this was the quickest way to fix that. Other options would include copying the libraries into the output directory, or not linking to the MinGW libraries and using only MSVCRT.

**Comment by qc316** [comment]
Hi,

On OS X, the patch is making nothing working !
By removing the two "set" instructions that were added, everything worked finally fine for me without installing anything else.

**Comment by hamish-milne** [comment]
Ah, okay - that sucks. Sorry about that.

Not sure what would really be causing it - all it does is tell the linker to include the libraries in the executables rather than looking for them elsewhere. It generally improves compatibility at the expense of program file size.

But if it's causing a problem, might be a good idea to put those two lines inside the WIN32 conditional block @m8pple 

For my curiosity, @qc316 could you post the error messages you got with those statements included?

**Comment by qc316** [comment]
Static binaries seems to don't be allowed on OS X : http://stackoverflow.com/questions/5259249/creating-static-mac-os-x-c-build
The error I got was the same as the one in the link above.

**Comment by hamish-milne** [comment]
Wow.. That's some real apple nonsense right there =P

Looks like the platform conditional is the right way to go at least.

**Comment by jeremych1000** [comment]
Interesting enough for me, this patch broke the ablity to compile test_opencl.cpp. Using the [last commit](https://github.com/HPCE/hpce-2016-cw3/blob/f8dba420e92d1059a8ba449308163f759d1dd5a9/CMakeLists.txt) does compile.

**Comment by davidanderle** [comment]
the -static line throws a warning in VS2017 and therefore it is completely ignored:

> warning LNK4012: invalid value 'X86;-static', must be 'ARM, EBC, HYBRID_X86_ARM64X64, or X86'; option ignored
