### ISSUE TITLE
test_opencl.cpp won't build in VMware Ubuntu environement

### ISSUE THREAD

**Issue by SantiagoRubioDev** [HPCE/hpce-2017-cw3#11]
I have been trying to compile/build/execute the test_opencl.cpp to see if I was missing anything. But whatever I try I get errors.

first I tried
`g++ -std=c++11 test_opencl.cpp -o test_opencl.o`
and got

```
src/test_opencl.cpp:21:21: fatal error: CL/cl.hpp: No such file or directory
compilation terminated.
```

so I tried
`g++ -I include -std=c++11 test_opencl.cpp -o test_opencl.o`
and got

```
src/test_opencl.cpp:169:22: fatal error: GL/gl.hpp: No such file or directory
compilation terminated.
```

so at this point I try to run provision.sh to install the files I am missing. But this line:
`sudo apt-get -y install amd-opencl-icd amd-libopencl1 amd-opencl-dev`
did not install anything it said they are all obsolete or have been removed.
but it told me I could install:  ocl-icd-opencl-dev instead

Once I did that I tried building test_opencl.cpp again and I get a new error a few hundred lines ending with:
`collect2: error: ld returned 1 exit status`

I tried using CMake but it fails for the same reason:

```
/usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
CMakeFiles/test_opencl.dir/build.make:121: recipe for target 'test_opencl' failed
make[2]: *** [test_opencl] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/test_opencl.dir/all' failed
make[1]: *** [CMakeFiles/test_opencl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

So obviously I am missing -lOpenCL but I don't know where to find it.

Is it even possible to use opencl in VMware if we don't have direct access to the gpu?
Would it be better for me to do CW3 on windows 7 directly?

Thanks in advance

**Comment by m8pple** [comment]
It is possible to use OpenCL, but only via a software provider. The
instructions I had used to work for software, setup, but it looks
like since I ran through the instructions over the summer the packages
have changed, and they have taken out the AMD provider.

One option is to use the DoC machines - quite a lot of the machines
have GPUs, and they have OpenCL installed.

In windows, the other reasonable alternative is to do it directly (e.g.
using the CMakeFile), or to use MinGW (this works quite well, and
you can use the headers/libs that are included in the spec).

**Comment by SantiagoRubioDev** [comment]
After trying for awhile I still wasn't able to make it work on VMware.
I am trying with MinGW now. But I get the same problem: CL/cl.hpp not found.
I manually added the file to C:\mingw\include\CL\cl.hpp.
I even tried adding the option -I  C:\mingw\include
I am sure it is looking at the right place because when adding option -v, it says where g++ looks for header files and C:\mingw\include is one of the path listed.

I am sure I am missing something really basic, but I cannot seem to make it work.
Hopefully if I know how to add headers, I will also be able to add the library

**Comment by m8pple** [comment]
Not sure if this is still an issue - afraid I was away over the weekend.

In MinGW (64-bit), I used:
- `-I include` : Bring in CL.hpp (if needed) and heat.hpp
- `-I opencl_sdk/include` : bring in the opencl headers. These are often provided by a system 
  header, but these ones should work as well.
- `-I opencl_sdk/lib/windows/x86_64` : This selects the libraries for windows and a 64-bit processor
- `-lOpenCL` : bring in the library.

```
dt10@GABBY MINGW64 ~
$ git clone https://github.com/HPCE/hpce-2016-cw3
Cloning into 'hpce-2016-cw3'...
remote: Counting objects: 127, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 127 (delta 0), reused 0 (delta 0), pack-reused 124
Receiving objects: 100% (127/127), 142.05 KiB | 0 bytes/s, done.
Resolving deltas: 100% (52/52), done.
Checking connectivity... done.

dt10@GABBY MINGW64 ~
$ cd hpce-2016-cw3/

dt10@GABBY MINGW64 ~/hpce-2016-cw3
$ g++ -I include -I opencl_sdk/include src/test_opencl.cpp -L opencl_sdk/lib/windows/x86_64 -lOpenCL

dt10@GABBY MINGW64 ~/hpce-2016-cw3
$
```

Does this work for you?

**Comment by SantiagoRubioDev** [comment]
I am still having issues. I couldn't do it with MinGW so I tried Visual Studio and for some reason it doesn't let me create a c++ console project anymore. I might have deleted some files that I thought were duplicates and ended up breaking something. I am currently reinstalling visual studio but it will probably take a few hours.

I tried the command you used above and this is my result:

```
C:\Users\Santiago\Rubio 2016\4th year\4th year modules\HPCE\CW3\hpce-2016-cw3-master>g++ -I include -I opencl_sdk/include -I src/test_opencl.cpp -L opencl_sdk/lib/windows/x86_64 -lOpencl
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../libmingw32.a(main.o):(.text.startup+0xa7): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
```

I have no idea what that means.

Also I do not know if it is related or not but I tried installing AMD APP SDK and it won't install anything because of a file being corrupt. I will add the exact error message once the Visual Studio finishes reinstalling, It won't let me try to install both at the same time.

Thanks for all the help.

**Comment by m8pple** [comment]
It means there is no main function in the executable.

I think you have an errant `-I` in front of `src/test_opencl.cpp`

**Comment by SantiagoRubioDev** [comment]
Sorry, that was a silly mistake. I took out the errant '-I'

Here is the real error message:

```

C:\Users\Santiago\Rubio 2016\4th year\4th year modules\HPCE\CW3\hpce-2016-cw3-master>g++ -I include -I opencl_sdk/include -std=c++11 src/test_opencl.cpp -L opencl_sdk/lib/windows/x86_64 -lOpencl
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl6detail16ReferenceHandlerIP11_cl_contextE7releaseES3_[__ZN2cl6detail16ReferenceHand
lerIP11_cl_contextE7releaseES3_]+0xd): undefined reference to `clReleaseContext@4'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl6detail16ReferenceHandlerIP17_cl_command_queueE7releaseES3_[__ZN2cl6detail16Referen
ceHandlerIP17_cl_command_queueE7releaseES3_]+0xd): undefined reference to `clReleaseCommandQueue@4'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl6detail16ReferenceHandlerIP7_cl_memE6retainES3_[__ZN2cl6detail16ReferenceHandlerIP7
_cl_memE6retainES3_]+0xd): undefined reference to `clRetainMemObject@4'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl6detail16ReferenceHandlerIP7_cl_memE7releaseES3_[__ZN2cl6detail16ReferenceHandlerIP
7_cl_memE7releaseES3_]+0xd): undefined reference to `clReleaseMemObject@4'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl6detail16ReferenceHandlerIP11_cl_programE7releaseES3_[__ZN2cl6detail16ReferenceHand
lerIP11_cl_programE7releaseES3_]+0xd): undefined reference to `clReleaseProgram@4'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl6detail16ReferenceHandlerIP10_cl_kernelE7releaseES3_[__ZN2cl6detail16ReferenceHandl
erIP10_cl_kernelE7releaseES3_]+0xd): undefined reference to `clReleaseKernel@4'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZNK2cl8Platform7getInfoEjPSs[__ZNK2cl8Platform7getInfoEjPSs]+0x21): undefined reference
to `clGetPlatformInfo@20'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZNK2cl8Platform10getDevicesEyPSt6vectorINS_6DeviceESaIS2_EE[__ZNK2cl8Platform10getDevice
sEyPSt6vectorINS_6DeviceESaIS2_EE]+0x4b): undefined reference to `clGetDeviceIDs@24'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZNK2cl8Platform10getDevicesEyPSt6vectorINS_6DeviceESaIS2_EE[__ZNK2cl8Platform10getDevice
sEyPSt6vectorINS_6DeviceESaIS2_EE]+0xd9): undefined reference to `clGetDeviceIDs@24'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl8Platform3getEPSt6vectorIS0_SaIS0_EE[__ZN2cl8Platform3getEPSt6vectorIS0_SaIS0_EE]+0x25): undefined reference to `clGetPlatformIDs@12'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl8Platform3getEPSt6vectorIS0_SaIS0_EE[__ZN2cl8Platform3getEPSt6vectorIS0_SaIS0_EE]+0x9c): undefined reference to `clGetPlatformIDs@12'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl7ContextC1ERKSt6vectorINS_6DeviceESaIS2_EEPiPFvPKcPKvjPvESC_S7_[__ZN2cl7ContextC1ER
KSt6vectorINS_6DeviceESaIS2_EEPiPFvPKcPKvjPvESC_S7_]+0x4a): undefined reference to `clCreateContext@24'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl6BufferC1ERKNS_7ContextEyjPvPi[__ZN2cl6BufferC1ERKNS_7ContextEyjPvPi]+0x53): undefined reference to `clCreateBuffer@24'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl7ProgramC1ERKNS_7ContextERKSt6vectorISt4pairIPKcjESaIS8_EEPi[__ZN2cl7ProgramC1ERKNS
_7ContextERKSt6vectorISt4pairIPKcjESaIS8_EEPi]+0x123): undefined reference to `clCreateProgramWithSource@20'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZNK2cl7Program5buildERKSt6vectorINS_6DeviceESaIS2_EEPKcPFvP11_cl_programPvESB_[__ZNK2cl7
Program5buildERKSt6vectorINS_6DeviceESaIS2_EEPKcPFvP11_cl_programPvESB_]+0x42):
undefined reference to `clBuildProgram@24'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl6KernelC1ERKNS_7ProgramEPKcPi[__ZN2cl6KernelC1ERKNS_7ProgramEPKcPi]+0x30): undefined reference to `clCreateKernel@12'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl12CommandQueueC1ERKNS_7ContextERKNS_6DeviceEyPi[__ZN2cl12CommandQueueC1ERKNS_7Conte
xtERKNS_6DeviceEyPi]+0x55): undefined reference to `clCreateCommandQueue@20'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZNK2cl12
CommandQueue17enqueueReadBufferERKNS_6BufferEjjjPvPKSt6vectorINS_5EventESaIS6_EE
PS6_[__ZNK2cl12CommandQueue17enqueueReadBufferERKNS_6BufferEjjjPvPKSt6vectorINS_
5EventESaIS6_EEPS6_]+0x8d): undefined reference to `clEnqueueReadBuffer@36'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZNK2cl12
CommandQueue18enqueueWriteBufferERKNS_6BufferEjjjPKvPKSt6vectorINS_5EventESaIS7_
EEPS7_[__ZNK2cl12CommandQueue18enqueueWriteBufferERKNS_6BufferEjjjPKvPKSt6vector
INS_5EventESaIS7_EEPS7_]+0x8d): undefined reference to `clEnqueueWriteBuffer@36'

C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZNK2cl12
CommandQueue20enqueueNDRangeKernelERKNS_6KernelERKNS_7NDRangeES6_S6_PKSt6vectorI
NS_5EventESaIS8_EEPS8_[__ZNK2cl12CommandQueue20enqueueNDRangeKernelERKNS_6Kernel
ERKNS_7NDRangeES6_S6_PKSt6vectorINS_5EventESaIS8_EEPS8_]+0xec): undefined refere
nce to `clEnqueueNDRangeKernel@36'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZNK2cl12
CommandQueue14enqueueBarrierEv[__ZNK2cl12CommandQueue14enqueueBarrierEv]+0x12):
undefined reference to `clEnqueueBarrier@4'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZN2cl6Ke
rnel6setArgINS_6BufferEEEijT_[__ZN2cl6Kernel6setArgINS_6BufferEEEijT_]+0x3a): un
defined reference to `clSetKernelArg@16'
C:\Users\Santiago\AppData\Local\Temp\ccMg7oUb.o:test_opencl.cpp:(.text$_ZNK2cl6D
evice7getInfoISsEEijPT_[__ZNK2cl6Device7getInfoISsEEijPT_]+0x21): undefined reference to `clGetDeviceInfo@20'
collect2.exe: error: ld returned 1 exit status
```

Visual Studio still hasn't finished reinstalling.

**Comment by m8pple** [comment]
Is your MinGW the 32-bit or the 64-bit version? I notice some references to `libmingw32`
above, which would suggest 32-bit.

The instructions above were for 64-bit MinGW, so if you want to select 32-bit then
change this:
- `-I opencl_sdk/lib/windows/x86_64` : This selects the libraries for windows and a 64-bit processor
  to this:
- `-I opencl_sdk/lib/windows/x86` : This selects the libraries for windows and a 32-bit build

**Comment by SantiagoRubioDev** [comment]
Thank you!
It works! For some reason I was sure I installed the 64 bit version. Maybe I am using a version that was already on my laptop and not the version I downloaded. But never mind, at least now I can start working on the actual course work!
