### ISSUE TITLE
MAC OS: Compiling Error

### ISSUE THREAD

**Issue by shl213** [HPCE/hpce-2017-cw3#12]
When I do make all to compile the system, I am getting an error saying

```
include/heat.hpp:19:15: error: expected identifier or '{'
        typedef enum : uint32_t{
                                ^
```
which leads on to failure in heat.cpp with undeclared identifiers regarding 'Cell_Insulator' and 'Cell_Fixed'

How should I solve this problem?

**Comment by m8pple** [comment]
It looks like the compiler is not selecting C++11 (i.e. modern C++):
- what compiler are you using (g++, clang++, xcode)?
- how are you building it (command-line, make, xcode, cmake)?
- can you check if c++11 needs to be enabled somehow?

In the makefile I used `-std=c++11` to turn it on, but the mechanism varies
with different platforms.

For some information on OS X, see:
- http://stackoverflow.com/questions/14228856/how-to-compile-c-with-c11-support-in-mac-terminal

**Comment by Szypicyn** [comment]
I have added the following lines to the top of makefile to fix this issue on a Mac. Not entirely sure whether I need the second one, but it seems to work for now.

CPP=clang++
CPPFLAGS=-g -std=c++11 -Wall -pedantic

Source: http://stackoverflow.com/questions/16886591/how-do-i-enable-c11-in-gcc
