### ISSUE TITLE
VMWare + Ubuntu 16

### ISSUE THREAD

**Issue by m8pple** [HPCE/hpce-2017-cw3#13]
> Regarding a question that is still open as an issue in cw3 involving the initial testing,
> I have been able to compile using this command in Ubuntu 16.04 VMWare:
>
>     g++ -I include -I opencl_sdk/include -std=c++11 src/test_opencl.cpp -o test_opencl.o -L. -lOpenCL
>
> after running the provision script and installing what was recommended. However,
> when I try to run the executable file, with or without sudo permissions, I
> always arrive at this error: Exception: clGetPlatformIDs. I have googled this
> with no success; have you perhaps seen this before?

This may well mean that you have successfully compiled the application, but
that there are no providers. As per issue #11, you'll need a software provider
to get things working, which in the provisioning script comes from the AMD
software provider.

When you ran the provisioning script, were there any errors? I think that
was the problem when the other person tried.

**Comment by m8pple** [comment]
Ah, I just realised that one of the problems people are having with the provisioning
script is that it is intended for Debian Jessie, not Ubuntu. It says that in the readme,
but not in the script itself.

**Comment by SantiagoRubioDev** [comment]
Is there anyway to make it work on Ubuntu?
I keep getting the error:
`Exception: clGetPlatformIDs`
I downloaded the AMD APP SDK. But I don't know how to reference it somehow when running the command 
`bin/test_opencl`

Any help would be much appriciated.

**Comment by SantiagoRubioDev** [comment]
Actually I just had to restart the session for the sdk to take effect. But now I have another error:

```
bin/test_opencl

Setting of real/effective user Id to 0/0 failed
modprobe: FATAL: Module fglrx not found in directory /lib/modules/4.4.0-45-generic
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
Found 1 platforms
  Platform 0 : Advanced Micro Devices, Inc.
Choosing platform 0
Found 1 devices
  Device 0 : Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
Choosing device 0
Success, program executed kernel successfully.
```

Same when executing v3_opencl:

```
bin/make_world | bin/spr13/step_world_v3_opencl > /dev/null

Setting of real/effective user Id to 0/0 failed
modprobe: FATAL: Module fglrx not found in directory /lib/modules/4.4.0-45-generic
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
Found 1 platforms
  Platform 0 : Advanced Micro Devices, Inc.
Choosing platform 0
Found 1 devices
  Device 0 : Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
Loaded world with w=128, h=128
Stepping by dt=0.1 for n=1

```

At least now the error does not terminate the program. How do I fix it? Should I just ignore it?

**Comment by jygoh1** [comment]
Ubuntu 16.04: still getting this error as well, also when I run the script I get the following issues with packages amd-opencl-icd and amd-libopencl1 (no installation candidate). However I can't seem to find an equivalent for Linux, and am still getting that clGetPlatformIDs error. Any advice would be great!

**Comment by SantiagoRubioDev** [comment]
To fix the clGetPlatormIDs error I download the AMD sdk version 2.8 from this site: http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/download-archive/
extract the file. execute the .sh instaltion file and once finished restart your session (shutdown/start)
That fixed it for me. I still have the modprobe: FATAL error but It seems like I can do the coursework nonetheless.
Hope that helps.

**Comment by m8pple** [comment]
Ah - ok, good.

I'll link this in from the readme, as it might help some people.
