### ISSUE TITLE
Can't build test_opencl.cpp on Linux

### ISSUE THREAD

**Issue by JHertz5** [HPCE/hpce-2017-cw3#15]
Hi

I'm running Linux Mint with an Intel integrated graphics processor. I have been trying to build test_opencl.cpp, but have been unsuccessful so far. I have installed the Intel OpenCL SDK and Driver, and as far as I can tell, they were successful, but the compilation was still unsuccessful. I tried to run provision.sh, but it came back with the following output
```
: No such file or directoryurces.list
./provision.sh: line 2: $'\r': command not found
E: Command line option 'y' [from -y] is not understood in combination with the other options.
./provision.sh: line 4: $'\r': command not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package perl
./provision.sh: line 6: $'\r': command not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package amd-libopencl1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ocl-icd-opencl-dev:i386 ocl-icd-opencl-dev

Package amd-opencl-icd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'amd-opencl-icd' has no installation candidate
E: Package 'amd-libopencl1' has no installation candidate
E: Unable to locate package amd-opencl-dev
./provision.sh: line 8: $'\r': command not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package freeglut3-dev
```
I installed ocl-icd-opencl-dev as suggested, but still cannot build test_opencl.cpp. Using the makefile, I get a long list of warnings in the style of 
"test_opencl.cpp:(.text.startup+0xc33): undefined reference to `NAME_OF_OPENCL_FUNCTION"
with "collect2: error: ld returned 1 exit status" at the end of the list. If I try building using cmake, I get an error saying "/usr/bin/ld: cannot find -lOpenCL".

I haven't managed to find a solution yet. Is it not working because of the integrated graphics processor?

**Comment by m8pple** [comment]
The message:

```
./provision.sh: line 2: $'\r': command not found
```

is something todo with dos vs unix line endings. I tend to run windows
editors, so sometimes they leak in.

Try running the utility `dos2unix` on the file, e.g.:

```
dos2unix provision.sh
```

That said, I don't think you should need to run the provisioning script
if you are running native and are using it as the desktop.

I've never used Linux Mint, so I don't really know the package manager. I believe
it is based on Debian or Ubuntu, so assuming it is using apt, you could try:

```
apt-cache search opencl
```

and see what comes back. From the error message you quote, a package
to try would be `ocl-icd-opencl-dev`:

```
apt-get install ocl-icd-opencl-dev
```

**Comment by m8pple** [comment]
Oh, and on the question of the integrated graphics card: I've successfully
used the integrated card on my Intel laptop. When I list devices, I get
one for the CPUs, and one for the GPUs.

**Comment by JHertz5** [comment]
Thanks for your reply. I had already run `apt-get install ocl-icd-opencl-dev` but the situation didn't improve. I'm just going to use AWS instead, so everything should be fine now. Thanks again!

**Comment by m8pple** [comment]
If you are doing the dev work (i.e. editing and development) on
AWS, then pay attention to the pricing. It's worth either getting a
cheap instance (e.g. a few CPUs) and using the software provider,
or get a GPU instances using the spot pricing approach. If you
use spot pricing, just make sure to save occasionally, in case the
price spikes (I usually bid at ~50% of the on-demand price, and
have never been kicked off an instance yet).
