### ISSUE TITLE
Error when executing test_opencl.cpp

### ISSUE THREAD

**Issue by SantiagoRubioDev** [HPCE/hpce-2017-cw3#16]
I am working with MinGW on Windows 7.

I used the command below to build the executable:
```
g++ -I include -I opencl_sdk/include -std=c++11 src/test_opencl.cpp -L opencl_sdk/lib/windows/x86 -lOpenCL -o src/test_opencl.exe
```
then go inside src and try to execute test_opencl:
```
cd src
test_opencl.exe
```
An error window pops:
```
Entry Point Not Found

The procedure entry point__gxx_personality_v0 could not be located in the dynamic link library libsrdc++-6.dll
```

Anyone had a similar issue? Am I suppose to add parameters/options when executing test_opencl.exe?

**Comment by SantiagoRubioDev** [comment]
I was able to fix it by copying the libsrdc++-6.dll file from C:/MinGW to the src folder.
That is not really convenient, is there anyway to do this without manually copying this driver in the directory of my executable every-time?

**Comment by zhiyb** [comment]
Maybe try setting the %PATH% variable, so that the libsrdc++-6.dll takes priority over the whatever other incompatible dlls

**Comment by SantiagoRubioDev** [comment]
Sorry I ended up going back to VMware instead of MinGW. I had to modify the makefile and except for test_opencl which gives me an exception for some reason everything else seems to work correctly.
