### ISSUE TITLE
Exception: clGetPlatformIDs

### ISSUE THREAD

**Issue by SantiagoRubioDev** [HPCE/hpce-2017-cw3#17]
I am using VMware Ubuntu

When executing test_opencl after successfully building it, I get this exception:
`Exception: clGetPlatformIDs`

Same when running step_world_v3_opencl after adding the choosing platform code:
```
bin/make_world | bin/spr13/step_world_v3_opencl > /dev/null

terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)
```

I guess I am missing a platform. What platform should I get and where?

**Comment by zhiyb** [comment]
Possibly a duplication of #13

**Comment by m8pple** [comment]
If you're willing to jump through the relevant manual installation hoops, then the
AMD APP SDK should work in a VM as well:

http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/

It's a little bit more involved than the standard `apt install` path, but I've previously had success
with it. I don't have the bandwidth where I am to pull an Ubuntu image and try it (I only have
a debian image locally), but I can look at it tomorrow and double-check the steps.

**Comment by m8pple** [comment]
Oops, I should have looked at the #13 link first.
