### ISSUE TITLE
Where to find HPCE-2015-GPU-Image

### ISSUE THREAD

**Issue by mattinmir** [HPCE/hpce-2017-cw3#19]
[Here](https://github.com/HPCE/hpce-2016-cw3#aws) it is mentioned there is a ready built AWS image for us to use but searching it in AWS AMI Community Marketplace returns [no results](https://i.imgur.com/Y6GeUpU.png). Am I looking in the wrong place?

**Comment by sagarpatel9410** [comment]
If you look in N.Virginia you will find it in the AWS AMI Community Marketplace

**Comment by mattinmir** [comment]
Weird that it is not in Ireland, but ok thanks
