### ISSUE TITLE
Setting up OpenCL on Windows

### ISSUE THREAD

**Issue by scutis** [HPCE/hpce-2017-cw3#2]
I've tried two different approaches on my laptop to set up OpenCL: Cygwin(1) and Visual Studio(2):

(1) Cygwin

With Cygwin (64bit version) I successfully built test_opencl.cpp using cmake. I also managed to build it by including/linking the correct .h and .lib files from Nvidia CUDA 7.5. However in both cases once I run test_opencl.exe the program crashes/freezes: no error/result is displayed, CTRL+C does not work and I cannot enter any new commands. If I try to then close cygwin, I get the warning message saying bash is still running.
Sometimes, while the program is running I get the following errors (but the program still doesn't stop executing and CTRL+C still does not work):

get_proc_lock: Couldn't acquire sync_proc_subproc for(5,1)
proc_subproc: couldn't get proc lock. what 5, val 1

(2) Visual Studio 2013
I managed to once again build test_opencl.cpp but once I run the executable the whole Visual Studio freezes and I can only terminate it from the task manager.

These are my system specs:

Windows 10 - 64bit
NVIDIA GEFORCE GTX 860M
i7-4710HQ CPU 2.5GHz

I simply do not understand where the problem comes from. Any ideas?

**Comment by m8pple** [comment]
At a guess that sounds like some kind of driver bug or error. If it's managing
to lock-up up VS, then something strange is going on (at least it's not crashing
the system, which is what usually happens with buggy OpenCL drivers).

Things to try:
- In visual studio, put a break-point at the start of main, then start the debugger.
  Single-step through the program, and try to identify the part that makes it
  freeze. You might need to use "Step-Into" as well as "Step-Over" in order
  to get through the C++ wrapper API and see which function call is causing
  the error. This might show if it's a more mundane error (file permissions
  or something like that).
- Use a tool like process explorer (https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) to work out exactly _where_ the
  program has crashed. Once the cygwin or visual studio program
  has frozen, find the corresponding process in processor explorer,
  and double-click to drill-down into the stack. This should tell you
  approximately where the crash is happening (e.g. is it in opencl.dll,
  or the executable).
- Try updating or reinstalling your graphics drivers. Windows 10 support may
  still be shaky, so this might be a known problem. Also, try to make sure
  you're on the WHQL version (unless that is known to be buggy).
- Try installing a software OpenCL implementation, e.g. the Intel:
  https://software.intel.com/en-us/articles/opencl-drivers
  or AMD:
  http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/
  implementations.
  Depending on where things are freezing, you might find that selecting a CPU
  only device lets the program start up.
- Try taking your compiled executable (the visual studio one) and run it on a different
  windows machine (e.g. a lab machine). In principle the same executable should be
  able to run on any x86-64 windows machine without extra libraries (though you may
  need to force the executable to statically link the C run-time library).

**Comment by scutis** [comment]
Thanks, I'll try to determine exactly where the program crashes then.
Meanwhile I managed to get openCL working on an older laptop (WIndows 7, GeForce G102M). So there's clearly nothing wrong with the way I build the project.

Anyway, I'll finish cw4 with the old laptop first but then I'll definitely come back to this issue.

**Comment by howchanghong** [comment]
I have issues with using CMake on Windows 10 as well. 

I followed the instructions which allowed me to build make_world, render_world and step_world. However, when it was building test_opencl.cpp.o, the following error occurs:

[ 83%] Building CXX object CMakeFiles/test_opencl.dir/src/test_opencl.cpp.o
In file included from /cygdrive/d/GitHub/hpce-2015-cw4/src/test_opencl.cpp:21:0:
/cygdrive/d/GitHub/hpce-2015-cw4/include/CL/cl.hpp: In member function ‘cl_int cl::CommandQueue::enqueueNativeKernel(void (_)(void_), std::pair<void*, unsigned int>, const std::vectorcl::Memory_, const std::vector<const void_>_, const std::vectorcl::Event_, cl::Event_) const’:
/cygdrive/d/GitHub/hpce-2015-cw4/include/CL/cl.hpp:2996:34: error: invalid conversion from ‘void (_)(void_)’ to ‘void (**attribute**((**stdcall**)) *)(void_)’ [-fpermissive](cl_event*) event),
                                  ^
In file included from /cygdrive/d/GitHub/hpce-2015-cw4/opencl_sdk/include/CL/opencl.h:42:0,
                 from /cygdrive/d/GitHub/hpce-2015-cw4/include/CL/cl.hpp:161,
                 from /cygdrive/d/GitHub/hpce-2015-cw4/src/test_opencl.cpp:21:
/cygdrive/d/GitHub/hpce-2015-cw4/opencl_sdk/include/CL/cl.h:960:1: note: initializing argument 2 of ‘cl_int clEnqueueNativeKernel(cl_command_queue, void (**attribute**((**stdcall**)) _)(void_), void_, size_t, cl_uint, _cl_mem_ const_, const void__, cl_uint, _cl_event_ const_, _cl_event__)’
 clEnqueueNativeKernel(cl_command_queue  /_ command_queue _/,
 ^
CMakeFiles/test_opencl.dir/build.make:86: recipe for target 'CMakeFiles/test_opencl.dir/src/test_opencl.cpp.o' failed
make[2]: *_\* [CMakeFiles/test_opencl.dir/src/test_opencl.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/test_opencl.dir/all' failed
make[1]: **\* [CMakeFiles/test_opencl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

I tried compiling the code using Visual Studio as well but the error message returned is the same.It would be great if you could point me to possible error points.

**Comment by howchanghong** [comment]
I have managed to solve the problem through suggestions by Sze Kiat to change the implementation to a 64bit version.

**Comment by m8pple** [comment]
@howchanghong  The problem you encountered seems to be with newer compilers
being more picky about function attributes. I've committed a patched version, which
fixed this problem for me on the latest Cygwin64 and Visual Studio (and still works
on others too).
