### ISSUE TITLE
Casting of Array in v2_function

### ISSUE THREAD

**Issue by Szypicyn** [HPCE/hpce-2017-cw3#20]
Having passed everything to the function I compiled it and got everything working apart from:

_world_properties_

I define the function as:

_void kernel_xy(uint32_t x, uint32_t y, uint32_t w, const float *world_state, float inner, float outer, float *buffer, const uint32_t *world_properties){ ... }_

And I call it as:

_kernel_xy(x,y,w, &world.state[0], inner, outer, &buffer[0], **&world.properties[0]**);_

I have checked and indeed heat.pp defines properties to be of type _cell_flags_t_ .This in turn is defined as uint32_t taking just two values. However when compiling the code I get the following error:

_src/jms13/step_world_v2_function.cpp:80:5: error: no matching function for call to 'kernel_xy'
                                kernel_xy(x,y,w, &world.state[0], inner, outer, &buffer[0], &world.properties[0]);
                                ^~~~~~~~~
src/jms13/step_world_v2_function.cpp:15:6: note: candidate function not viable: no known conversion from 'value_type *'
      (aka 'hpce::cell_flags_t *') to 'const uint32_t *' (aka 'const unsigned int *') for 8th argument
void kernel_xy(uint32_t x, uint32_t y, uint32_t w, const float *world_state, float inner, float outer, float *buffer, const uint3...
     ^_

You do say that world.properies should be casted first (that is a new concept to me). I have tried the following:f

_kernel_xy(x,y,w, &world.state[0], inner, outer, &buffer[0], **&(uint32_t)world.properties[0]**);_

But the error that I then get is:

_cannot take the address of an rvalue of type 'uint32_t' _

What is happening here and how do cast an array/vector?

**Comment by JHertz5** [comment]
I believe it should be 
`(const uint32_t *)&world.properties[0]`
 or just 
`(uint32_t *)&world.properties[0]`
if your kernel_xy doesn't specify the input as a const

**Comment by Szypicyn** [comment]
Works, cheers.
