### ISSUE TITLE
Error when building test_opencl on AWS

### ISSUE THREAD

**Issue by sagarpatel9410** [HPCE/hpce-2017-cw3#21]
I have started a new EC2 instance on AWS with the image supplied, I am trying to compile using the command

`g++ -std=c++11 -I include -I opencl_sdk/include src/test_opencl.cpp`

however I am getting the following error:

/tmp/cckMMKmt.o: In function `cl::detail::ReferenceHandler<_cl_context*>::release(_cl_context*)':
test_opencl.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP11_cl_contextE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP11_cl_contextE7releaseES3_]+0x14): undefined reference to `clReleaseContext'
/tmp/cckMMKmt.o: In function `cl::detail::ReferenceHandler<_cl_command_queue*>::release(_cl_command_queue*)':
test_opencl.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP17_cl_command_queueE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP17_cl_command_queueE7releaseES3_]+0x14): undefined reference to `clReleaseCommandQueue'
/tmp/cckMMKmt.o: In function `cl::detail::ReferenceHandler<_cl_mem*>::retain(_cl_mem*)':
test_opencl.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP7_cl_memE6retainES3_[_ZN2cl6detail16ReferenceHandlerIP7_cl_memE6retainES3_]+0x14): undefined reference to `clRetainMemObject'
/tmp/cckMMKmt.o: In function `cl::detail::ReferenceHandler<_cl_mem*>::release(_cl_mem*)':
test_opencl.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP7_cl_memE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP7_cl_memE7releaseES3_]+0x14): undefined reference to `clReleaseMemObject'
/tmp/cckMMKmt.o: In function `cl::detail::ReferenceHandler<_cl_program*>::release(_cl_program*)':
test_opencl.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP11_cl_programE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP11_cl_programE7releaseES3_]+0x14): undefined reference to `clReleaseProgram'
/tmp/cckMMKmt.o: In function `cl::detail::ReferenceHandler<_cl_kernel*>::release(_cl_kernel*)':
test_opencl.cpp:(.text._ZN2cl6detail16ReferenceHandlerIP10_cl_kernelE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP10_cl_kernelE7releaseES3_]+0x14): undefined reference to `clReleaseKernel'
/tmp/cckMMKmt.o: In function `cl::Platform::getInfo(unsigned int, std::string*) const':
test_opencl.cpp:(.text._ZNK2cl8Platform7getInfoEjPSs[_ZNK2cl8Platform7getInfoEjPSs]+0x22): undefined reference to `clGetPlatformInfo'
/tmp/cckMMKmt.o: In function `cl::Platform::getDevices(unsigned long, std::vector<cl::Device, std::allocator<cl::Device> >*) const':
test_opencl.cpp:(.text._ZNK2cl8Platform10getDevicesEmPSt6vectorINS_6DeviceESaIS2_EE[_ZNK2cl8Platform10getDevicesEmPSt6vectorINS_6DeviceESaIS2_EE]+0x3b): undefined reference to `clGetDeviceIDs'
test_opencl.cpp:(.text._ZNK2cl8Platform10getDevicesEmPSt6vectorINS_6DeviceESaIS2_EE[_ZNK2cl8Platform10getDevicesEmPSt6vectorINS_6DeviceESaIS2_EE]+0xb8): undefined reference to `clGetDeviceIDs'
/tmp/cckMMKmt.o: In function `cl::Platform::get(std::vector<cl::Platform, std::allocator<cl::Platform> >*)':
test_opencl.cpp:(.text._ZN2cl8Platform3getEPSt6vectorIS0_SaIS0_EE[_ZN2cl8Platform3getEPSt6vectorIS0_SaIS0_EE]+0x25): undefined reference to `clGetPlatformIDs'
test_opencl.cpp:(.text._ZN2cl8Platform3getEPSt6vectorIS0_SaIS0_EE[_ZN2cl8Platform3getEPSt6vectorIS0_SaIS0_EE]+0x98): undefined reference to `clGetPlatformIDs'
/tmp/cckMMKmt.o: In function `cl::Context::Context(std::vector<cl::Device, std::allocator<cl::Device> > const&, long*, void (*)(char const*, void const*, unsigned long, void*), void*, int*)':
test_opencl.cpp:(.text._ZN2cl7ContextC2ERKSt6vectorINS_6DeviceESaIS2_EEPlPFvPKcPKvmPvESC_Pi[_ZN2cl7ContextC5ERKSt6vectorINS_6DeviceESaIS2_EEPlPFvPKcPKvmPvESC_Pi]+0x6c): undefined reference to `clCreateContext'
/tmp/cckMMKmt.o: In function `cl::Buffer::Buffer(cl::Context const&, unsigned long, unsigned long, void*, int*)':
test_opencl.cpp:(.text._ZN2cl6BufferC2ERKNS_7ContextEmmPvPi[_ZN2cl6BufferC5ERKNS_7ContextEmmPvPi]+0x53): undefined reference to `clCreateBuffer'
/tmp/cckMMKmt.o: In function `cl::Program::Program(cl::Context const&, std::vector<std::pair<char const*, unsigned long>, std::allocator<std::pair<char const*, unsigned long> > > const&, int*)':
test_opencl.cpp:(.text._ZN2cl7ProgramC2ERKNS_7ContextERKSt6vectorISt4pairIPKcmESaIS8_EEPi[_ZN2cl7ProgramC5ERKNS_7ContextERKSt6vectorISt4pairIPKcmESaIS8_EEPi]+0x15a): undefined reference to `clCreateProgramWithSource'
/tmp/cckMMKmt.o: In function `cl::Program::build(std::vector<cl::Device, std::allocator<cl::Device> > const&, char const*, void (*)(_cl_program*, void*), void*) const':
test_opencl.cpp:(.text._ZNK2cl7Program5buildERKSt6vectorINS_6DeviceESaIS2_EEPKcPFvP11_cl_programPvESB_[_ZNK2cl7Program5buildERKSt6vectorINS_6DeviceESaIS2_EEPKcPFvP11_cl_programPvESB_]+0x5f): undefined reference to `clBuildProgram'
/tmp/cckMMKmt.o: In function `cl::Kernel::Kernel(cl::Program const&, char const*, int*)':
test_opencl.cpp:(.text._ZN2cl6KernelC2ERKNS_7ProgramEPKcPi[_ZN2cl6KernelC5ERKNS_7ProgramEPKcPi]+0x43): undefined reference to `clCreateKernel'
/tmp/cckMMKmt.o: In function `cl::CommandQueue::CommandQueue(cl::Context const&, cl::Device const&, unsigned long, int*)':
test_opencl.cpp:(.text._ZN2cl12CommandQueueC2ERKNS_7ContextERKNS_6DeviceEmPi[_ZN2cl12CommandQueueC5ERKNS_7ContextERKNS_6DeviceEmPi]+0x59): undefined reference to `clCreateCommandQueue'
/tmp/cckMMKmt.o: In function `cl::CommandQueue::enqueueReadBuffer(cl::Buffer const&, unsigned int, unsigned long, unsigned long, void*, std::vector<cl::Event, std::allocator<cl::Event> > const*, cl::Event*) const':
test_opencl.cpp:(.text._ZNK2cl12CommandQueue17enqueueReadBufferERKNS_6BufferEjmmPvPKSt6vectorINS_5EventESaIS6_EEPS6_[_ZNK2cl12CommandQueue17enqueueReadBufferERKNS_6BufferEjmmPvPKSt6vectorINS_5EventESaIS6_EEPS6_]+0xa1): undefined reference to `clEnqueueReadBuffer'
/tmp/cckMMKmt.o: In function `cl::CommandQueue::enqueueWriteBuffer(cl::Buffer const&, unsigned int, unsigned long, unsigned long, void const*, std::vector<cl::Event, std::allocator<cl::Event> > const*, cl::Event*) const':
test_opencl.cpp:(.text._ZNK2cl12CommandQueue18enqueueWriteBufferERKNS_6BufferEjmmPKvPKSt6vectorINS_5EventESaIS7_EEPS7_[_ZNK2cl12CommandQueue18enqueueWriteBufferERKNS_6BufferEjmmPKvPKSt6vectorINS_5EventESaIS7_EEPS7_]+0xa1): undefined reference to `clEnqueueWriteBuffer'
/tmp/cckMMKmt.o: In function `cl::CommandQueue::enqueueNDRangeKernel(cl::Kernel const&, cl::NDRange const&, cl::NDRange const&, cl::NDRange const&, std::vector<cl::Event, std::allocator<cl::Event> > const*, cl::Event*) const':
test_opencl.cpp:(.text._ZNK2cl12CommandQueue20enqueueNDRangeKernelERKNS_6KernelERKNS_7NDRangeES6_S6_PKSt6vectorINS_5EventESaIS8_EEPS8_[_ZNK2cl12CommandQueue20enqueueNDRangeKernelERKNS_6KernelERKNS_7NDRangeES6_S6_PKSt6vectorINS_5EventESaIS8_EEPS8_]+0x115): undefined reference to `clEnqueueNDRangeKernel'
/tmp/cckMMKmt.o: In function `cl::CommandQueue::enqueueBarrier() const':
test_opencl.cpp:(.text._ZNK2cl12CommandQueue14enqueueBarrierEv[_ZNK2cl12CommandQueue14enqueueBarrierEv]+0x17): undefined reference to `clEnqueueBarrier'
/tmp/cckMMKmt.o: In function `int cl::Kernel::setArg<cl::Buffer>(unsigned int, cl::Buffer)':
test_opencl.cpp:(.text._ZN2cl6Kernel6setArgINS_6BufferEEEijT_[_ZN2cl6Kernel6setArgINS_6BufferEEEijT_]+0x43): undefined reference to `clSetKernelArg'
/tmp/cckMMKmt.o: In function `int cl::Device::getInfo<std::string>(unsigned int, std::string*) const':
test_opencl.cpp:(.text._ZNK2cl6Device7getInfoISsEEijPT_[_ZNK2cl6Device7getInfoISsEEijPT_]+0x22): undefined reference to `clGetDeviceInfo'
collect2: error: ld returned 1 exit status

How do I fix this?

**Comment by zhiyb** [comment]
Try adding -lOpenCL to linker flags, to link to the OpenCL dynamic library

**Comment by sagarpatel9410** [comment]
Awesome thanks
