### ISSUE TITLE
Error compiling test_opencl AWS

### ISSUE THREAD

**Issue by Gar1G** [HPCE/hpce-2017-cw3#22]
Ive just started an instance on AWS and trying to compile the test_opencl with the command:

`g++ -std=c++11 -I include -I opencl_sdk/include src/test_opencl.cpp -lOpenCL`

I included the link to the OpenCL library as mentioned in the previous issue before this but still getting this error:

src/test_opencl.cpp: In function ‘int main(int, char**)’:
src/test_opencl.cpp:73:67: error: no matching function for call to ‘cl::Device::getInfo()’
    std::string ver=devices[i].getInfo<CL_DEVICE_OPENCL_C_VERSION>();
                                                                   ^
src/test_opencl.cpp:73:67: note: candidates are:
In file included from src/test_opencl.cpp:22:0:
include/CL/cl.hpp:1201:12: note: template<class T> cl_int cl::Device::getInfo(cl_device_info, T*) const
     cl_int getInfo(cl_device_info name, T* param) const
            ^
include/CL/cl.hpp:1201:12: note:   template argument deduction/substitution failed:
include/CL/cl.hpp:1210:5: note: template<int name> typename cl::detail::param_traits<cl::detail::cl_device_info, name>::param_type cl::Device::getInfo(cl_int*) const
     getInfo(cl_int* err = NULL) const
     ^
include/CL/cl.hpp:1210:5: note:   template argument deduction/substitution failed:
include/CL/cl.hpp: In substitution of ‘template<int name> typename cl::detail::param_traits<cl::detail::cl_device_info, name>::param_type cl::Device::getInfo(cl_int*) const [with int name = 4157]’:
src/test_opencl.cpp:73:67:   required from here
include/CL/cl.hpp:1210:5: error: no type named ‘param_type’ in ‘struct cl::detail::param_traits<cl::detail::cl_device_info, 4157>’
src/test_opencl.cpp:84:29: error: no matching function for call to ‘cl::Context::Context(cl::Device&)’
   cl::Context context(device);
                             ^
src/test_opencl.cpp:84:29: note: candidates are:
In file included from src/test_opencl.cpp:22:0:
include/CL/cl.hpp:1466:5: note: cl::Context::Context(const cl::Context&)
     Context(const Context& context) : detail::Wrapper<cl_type>(context) { }
     ^
include/CL/cl.hpp:1466:5: note:   no known conversion for argument 1 from ‘cl::Device’ to ‘const cl::Context&’
include/CL/cl.hpp:1464:5: note: cl::Context::Context()
     Context() : detail::Wrapper<cl_type>() { }
     ^
include/CL/cl.hpp:1464:5: note:   candidate expects 0 arguments, 1 provided
include/CL/cl.hpp:1443:5: note: cl::Context::Context(cl_device_type, cl_context_properties*, void (*)(const char*, const void*, size_t, void*), void*, cl_int*)
     Context(
     ^
include/CL/cl.hpp:1443:5: note:   no known conversion for argument 1 from ‘cl::Device’ to ‘cl_device_type {aka long unsigned int}’
include/CL/cl.hpp:1420:5: note: cl::Context::Context(const std::vector<cl::Device>&, cl_context_properties*, void (*)(const char*, const void*, size_t, void*), void*, cl_int*)
     Context(
     ^
include/CL/cl.hpp:1420:5: note:   no known conversion for argument 1 from ‘cl::Device’ to ‘const std::vector<cl::Device>&’

**Comment by pierrezaza** [comment]
I have almost the same error on my Macbook Pro. I've tried running a test_opencl.cpp file from someone else's computer and it turned out they were different. It looks like in the latest commit the line `std::string ver=devices[i].getInfo<CL_DEVICE_OPENCL_C_VERSION>();` was added, and it seems to be causing issues. The test_opencl.cpp that works on my Mac doesn't have this line. Try commenting the line (you'll have to modify the line below which prints the result).

**Comment by m8pple** [comment]
Ok, this might be a difference in "CL/cl.hpp" versions, as there will be
different versions on different platforms and SDKs.

So my understanding is this will work (I can't test things at the moment, as doing
something else) :

```
    for(unsigned i=0;i<devices.size();i++){
        std::string name=devices[i].getInfo<CL_DEVICE_NAME>();
        //std::string ver=devices[i].getInfo<CL_DEVICE_OPENCL_C_VERSION>();
        //std::cerr<<"  Device "<<i<<" : "<<name<<", version: "<<ver<<"\n";
        std::cerr<<"  Device "<<i<<" : "<<name<<"\n";
    }
```

?

If so, I'll edit the master version.

**Comment by mattinmir** [comment]
@Gar1G Did this work? I am having the same problem. If so, maybe submit a pull request?

**Comment by zhiyb** [comment]
Fix for
`src/test_opencl.cpp:84:29: error: no matching function for call to ‘cl::Context::Context(cl::Device&)’
cl::Context context(device);`
in #28
