### ISSUE TITLE
V4 renders only initial state

### ISSUE THREAD

**Issue by Szypicyn** [HPCE/hpce-2017-cw3#24]
Is there a mistake in the CW code? I can't render anything other the initial state with the v4 version.
Having simplified the loop by taking out the writes to and from GPU memory my code looks like that

```
	queue.enqueueWriteBuffer(buffProperties, CL_TRUE, 0, cbBuffer, &world.properties[0]);

	cl::NDRange offset(0, 0);               // Always start iterations at x=0, y=0
	cl::NDRange globalSize(w, h);   // Global size must match the original loops
	cl::NDRange localSize=cl::NullRange;    // We don't care about local size

	queue.enqueueWriteBuffer(buffState, CL_TRUE, 0, cbBuffer, &world.state[0]);
	std::vector<float> buffer(w*h);

	for(unsigned t=0;t<n;t++){		
		
		kernel.setArg(3, buffState);
        	kernel.setArg(4, buffBuffer);
		
		queue.enqueueNDRangeKernel(kernel, offset, globalSize, localSize);
		
		queue.enqueueBarrier();

		std::swap(buffState, buffBuffer);
	
		world.t += dt;
		
	} // end of for(t...

	queue.enqueueReadBuffer(buffBuffer, CL_TRUE, 0, cbBuffer, &buffer[0]); 
  
```

It compiles, however when running it, it only renders the initial state of the world.
I.e. when I execute 
`bin/make_world 100 0.1 | bin/jms13/step_world_v4_double_buffered 0.1 10000 | bin/render_world dump.bmp`

I get 
![dump](https://cloud.githubusercontent.com/assets/22754675/19939463/04aab122-a121-11e6-970f-1bc97aa604dc.png)

I can't seem to figure this out...
V3 worked fine.

**Comment by m8pple** [comment]
I notice that your final read back is into a vector called `buffer`. Does the data then
get transferred back into `world.state`? (Do you even need `buffer`).

**Comment by Szypicyn** [comment]
Of course.... Thank you.
