### ISSUE TITLE
Differences between v0,v1,v2 and v3

### ISSUE THREAD

**Issue by jeremych1000** [HPCE/hpce-2017-cw3#25]
Just finished v3 and did a test to see if the output is consistent with the previous few exercises and there seems to be some small numerical error. Is this to do with uint32, float, etc?

Command: `Measure-Command { .\bin\Debug\make_world.exe 10 0.1 | .\bin\Debug\step_world.exe 0.1 10 > o.txt }; Measure-Command { .\bin\Debug\make_world.exe 10 0.1 | .\bin\Debug\step_world_v3_opencl.exe 0.1 10 > o3.txt }; Compare-Object (Get-Content o.txt) (Get-Content o3.txt)`

```
Loaded world with w=10, h=10
Stepping by dt=0.1 for n=10
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 113
Ticks             : 1133834
TotalDays         : 1.31230787037037E-06
TotalHours        : 3.14953888888889E-05
TotalMinutes      : 0.00188972333333333
TotalSeconds      : 0.1133834
TotalMilliseconds : 113.3834

Loaded world with w=10, h=10
Stepping by dt=0.1 for n=10
Found 2 platforms
  Platform 0 : NVIDIA Corporation
  Platform 1 : Intel(R) Corporation
Choosing platform 0
Found 1 devices
  Device 0 : GeForce GTX 970
Choosing device 0
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 356
Ticks             : 3560283
TotalDays         : 4.12069791666667E-06
TotalHours        : 9.889675E-05
TotalMinutes      : 0.005933805
TotalSeconds      : 0.3560283
TotalMilliseconds : 356.0283


InputObject   :  0.00000000 0.09400841 0.09320582 0.09317092 0.09316998 0.09316746 0.09304091 0.08869656 0.08929560
                0.00000000
SideIndicator : =>


InputObject   :  0.00000000 0.09400839 0.09320582 0.09317093 0.09316999 0.09316747 0.09304092 0.08869657 0.08929561
                0.00000000
SideIndicator : <=
```

**Comment by m8pple** [comment]
Ooh, PowerShell! Good to see other scripting languages being used.

Yes, I think you're seeing the very small artifacts due to single-precision
variations.

Looking at the first entry:

```
(0.09400841 - 0.09400839) / 0.09400841 ~= 2.1274e-7
```

Single-precision has about 24-bits of relative precision, which is

```
2^-24 ~= 5.9604e-8
```

So after 10 iterations, that feels about right.

**Comment by jeremych1000** [comment]
Good to know. Will this be a problem for your coursework testing? Or does it use some kind of fuzzy matching :o

**Comment by m8pple** [comment]
The tester uses an epsilon based comparison, so it looks for:

   abs( (ref-got) / ref ) < eps

The value of eps is chosen based on some heuristics about how many
operations are done, and how much error might accumulate as a result
(it is pretty generous, just in case).
