### ISSUE TITLE
problem on checking OpenCL environment on Ubuntu

### ISSUE THREAD

**Issue by lynx5120** [HPCE/hpce-2017-cw3#27]
I have run the provision script and my computer (Ubuntu 14.04) cannot find amd-opencl-icd, amd-libopencl1 and amd-opencl-dev. 

However, I have a Nvidia GPU. Can I do this coursework with a Nvidia OpenCL package (like nvidia-opencl-dev )? It is not different, right?

**Comment by m8pple** [comment]
Yes, you can definitely can and should use the NVidia OpenCL for your card.

The provision script is really only for VMs, and only Debian Jessie (I get the
impression it is causing more confusion than it is helping).

**Comment by lynx5120** [comment]
Thank you! :)
