### ISSUE TITLE
V4 failing test

### ISSUE THREAD

**Issue by sagarpatel9410** [HPCE/hpce-2017-cw3#29]
I have implemented v4 and compared it to the reference: 
https://github.com/HPCE/hpce-2016-cw3-sp3613/blob/master/Picture1.png

As you can see the difference between the reference values and v4 values are small, however I am still failing your test.

I am wondering if this is a problem with me or the test?

Thanks

**Comment by jeremych1000** [comment]
Similar to issue #25, also we can't view your private repo.

**Comment by sagarpatel9410** [comment]
Sorry, http://imgur.com/a/Ui29v
