### ISSUE TITLE
EC2 GPU Instance Limits?

### ISSUE THREAD

**Issue by liafalk** [HPCE/hpce-2017-cw3#31]
Hi!
Is it possible to clone the AMI into the Ireland availability region?
For some reason my account isn't allowed to create GPU instances- I've had to ask them to increase the limit, and they have, but it only applies to Ireland. I've asked them to do the same for N. Virginia but it took them a few days last time so I'm not expecting a reply anytime soon...

Or am I possibly doing something wrong here?

**Comment by liafalk** [comment]
I got everything up and running on Ireland with a blank debian image. Turns out my problems were to do with the CMake file (I misread the issue about it). Not sure if the drivers are configured correctly though.

Still curious how it seems like no-one else has an instance limit, but oh well.

**Comment by eugenius1** [comment]
@indigo-  I had the GPU instance limit yesterday. I made an increase request. You have to describe that you're doing a university course with GPUs.
I don't know how CMake relates to AWS's instance limits though.

**Comment by liafalk** [comment]
@eugenius1 Yep I already got access to the Ireland GPU instances. I originally meant that I wanted the pre-built AMI image since I was having problems with compiling the OpenCL code - I thought I misconfigured the Nvidia drivers on my own image but it was actually just a CMake issue... No problems anymore 👍
