### ISSUE TITLE
CPU vs GPU (Integrated) - No SpeedUp between V4 and V5

### ISSUE THREAD

**Issue by narobertson42** [HPCE/hpce-2017-cw3#32]
Has anybody experienced no speed up between V4 and V5 when using an integrated GPU? I'm not sure if this is a result of setting `packed` vector taking too long or if there is some architectural reason that makes the difference between memory space read/write negligible. 

Version | Intel Core i5-4258U Time (secs) | Intel Iris Time (secs)
------------ | ------------- | -------------
Original | 8.662 | 8.662
Version 3 | 7.414 | 3.369
Version 4 | 6.094 | 1.479
Version 5 | 4.868 | 1.492

**Comment by m8pple** [comment]
Integrated GPUs often have different memory profiles, with less of a penalty
for accessing global memory. They are often less intrinsically parallel (fewer
effective compute units), so the memory/compute ratio can be better
balanced. On some GPUs the packed version can actually
be slower, though I've never seen that on a discrete or server-class GPU.

**Comment by jeremych1000** [comment]
@m8pple I have a discrete Nvidia GPU and do experience speed up between v4 and v5, however it is very variable and ranges from 1.01x to 1.1x. For example, when using world size; step size 5000;1000 I have a 1.027x speedup, when using your test script 256;2048 I have a 1.1x speedup. I have already added some optimizations during packing - should I be looking to do more?
