### ISSUE TITLE
making the isolation clean

### ISSUE THREAD

**Issue by lynx5120** [HPCE/hpce-2017-cw3#33]
When I did [making the isolation clean](https://github.com/HPCE/hpce-2016-cw3#making-the-isolation-clean),  by adding parameter `const uint32_t * world_properties`, and I got an error:

`error: cannot convert ‘__gnu_cxx::__alloc_traits<std::allocator<hpce::cell_flags_t> >::value_type* {aka hpce::cell_flags_t*}’ to ‘uint32_t* {aka unsigned int*}’ for argument ‘5’ to ‘void kernel_xy(uint32_t, uint32_t, uint32_t, const float*, uint32_t*, float*, float, float)’`

Argument 5 here is the `world_properties`, any clue?

And then I tried to change the type into hpce::cell_flags_t, then it works. But here it says:

> When it comes to passing the cell properties, note that cell_flags_t was originally defined to have the underlying type uint32_t, so you can safely cast to a (const uint32_t *) when converting parameters.

Hmm, A little confused.

**Comment by eugenius1** [comment]
Type cast when you pass in the parameter, like this: `(uint32_t *)&world.properties[0]`
Check out the solution to issue #20 .

**Comment by m8pple** [comment]
Oops, forgot to close last year.
