### ISSUE TITLE
CMake linking error under Ubuntu

### ISSUE THREAD

**Issue by patengelbert** [HPCE/hpce-2017-cw3#37]
On Ubuntu the default libraries installed from apt-get are made to be dynamically linked. (libOpenCl.so).

On the CMake due to Windows dll errors, it forces the use of static libraries.

This leads to the following error message:

```sh
[ 25%] Linking CXX executable step_world
/usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
make[2]: *** [step_world] Error 1
make[1]: *** [CMakeFiles/step_world.dir/all] Error 2
make: *** [all] Error 2
```

The cause of this is the following two lines in the CMakeLists.txt:

```CMake
set(BUILD_SHARED_LIBS OFF)
set(CMAKE_EXE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS} "-static")
```

If these lines are commented out, builds on Ubuntu with static libraries work

**Comment by m8pple** [comment]
I'll leave this open so that people can see it.

The CMake thing became a bit of an issue, I'll look into more formally
supporting it next time.

**Comment by janscholten** [comment]
Thank you so much! I've I had only knew this 7 hours ago...
