### ISSUE TITLE
Failing Tests 26 and 27

### ISSUE THREAD

**Issue by narobertson42** [HPCE/hpce-2017-cw3#38]
`nar213, 26, For n=256, steps=2048: Check time for v3 (Command exited with non-zero status 1 0.02) is more than 1.2 x v4 (Command exited with non-zero status 1 0.02), FAIL
true
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
nar213, 27, For n=256, steps=2048: Check time for v4 (Command exited with non-zero status 1 0.02) is more than 1.05 x v5 (Command exited with non-zero status 1 0.02), FAIL
`

Has anybody passed Tests 26 and 27? I've tried running with n=256 and steps=2048 on my local device and it seems to work fine for both V3 and V4.

**Comment by alino95** [comment]
Personally I have had a few problems in compilation so I would not know. Many people are failing those tests though. When I run the test locally I _just_ pass the test (MacBook Air 11inch 2012).

**Comment by alino95** [comment]
Personally I have had a few problems in compilation so I would not know. Many people are failing those tests though. When I run the test locally I _just_ pass it (MacBook Air 11inch 2012).

**Comment by sagarpatel9410** [comment]
I have been having the same problem, failing only test 26 & 27, I ran the test on a GPU instance and c4.8xLarge Instance and these tests appear to pass.

**Comment by jeremych1000** [comment]
Try running it multiple times and see if its always faster/slower. If I run it 5 times in a row I get varying results for each time. Sometimes it passes, sometimes it fails.
