### ISSUE TITLE
Automated Tests

### ISSUE THREAD

**Issue by alino95** [HPCE/hpce-2017-cw3#39]
I have had a few problem in compilation in the automated test. Clearly it works perfectly fine on my machine. 

Is it possible to know on what platform the scripts are run onto? Is it on the same _HPCE-2015-GPU-Image_ on AWS?

**Comment by m8pple** [comment]
The ones that have the (AWS) flag in the commit message are from
`HPCE-2015-GPU-Image`, or are at least intended to be (I think I'm
using that image when I boot it). The other ones (Non AWS) are
from a virtual machine that is only approximately the same.

What are the compilation errors?

**Comment by m8pple** [comment]
Another one I forgot to close last year.
