### ISSUE TITLE
V3 output does not entirely match original output

### ISSUE THREAD

**Issue by tahmid95** [HPCE/hpce-2017-cw3#40]
Some of us have noticed that when comparing the V3 output to the output of the original step world function, there are slight differences in the values. When the step is 1 this does not occur but as you increase it the number of mismatching values shown by diff increases. Is this due to the minute differences in the floating point calculations by the cpu and gpu?

**Comment by jeremych1000** [comment]
#25 #29 

v3 will be different to v2/1, but should be the same as v4 and v5.

| Algorithm | Hash of output .bmp file | Implementation |
| --- | --- | --- |
| SHA1 | 72816CBC472018FD895BB35AB39B722259CF5119 | v2 |
| SHA1 | AD6BC5F65E5FC7EF98D57F6279A1FB685AF8BFA7 | v3 |
| SHA1 | AD6BC5F65E5FC7EF98D57F6279A1FB685AF8BFA7 | v4 |
| SHA1 | AD6BC5F65E5FC7EF98D57F6279A1FB685AF8BFA7 | v5 |
