### ISSUE TITLE
Minor Difference in results CPU vs GPU

### ISSUE THREAD

**Issue by jake2184** [HPCE/hpce-2017-cw3#5]
I have compiled and run the kernel on my GPU, and output the results into a dump file. I have done the same with the original code. I then compare these using diff.

I get no errors for stepping 1 or 2 times. I increase steps to 50/100, and get minor differences in the outputted values. Given that it works for small steps and not for larger ones, I am assuming this is do to a rounding error or different levels of accuracy. 

Is this incorrect, or simply architectural differences? Is there a way to minimise or remove this error, or shall I leave it as acceptable? It makes quick checks a little bit harder to do, and it vaguely irritating.

For an example of the size of error, for the command:

```
   ./bin/make_world 10 0.1 | ./bin/step_world_v3_opencl 0.1 100 > bin/test4.txt
```

I get a cell value of 0.62648118 rather than 0.62648082, an error of 0.000057%.

I am using Ubuntu 64bit, with an nVidia GT 220.

**Comment by jake2184** [comment]
In addition, the initial GPU execution is about 10x faster than the CPU, rather than slower as suggested. Missing something out?

**Comment by m8pple** [comment]
It's almost certainly something to do with floating-point re-association, or the
GPU using an fused multiply accumulate (FMA) internally. The error you're
getting looks like it is at the level of floating-point round-off error:

```
>> -log2(0.000057/100)
ans =
    20.7425
```

We get about 24 bits of precision with single precision, so it looks like the
accuracy has dropped down to just about 21 bits, which sounds reasonable.
after 100 steps.

There is a pragma for stopping contraction of FMAs:
https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/FP_CONTRACT.html

I've never actually tried using it though.

IIRC, when I test I use a little custom diff program, which uses a tolerance
to compare the two results.

Regarding speed, conceivably the GPU _could_ be faster even in the first GPU
version, if the software is relatively slow, and the GPU is fast/has low-overhead
startup (e.g. in a fusion part, where the GPU and CPU are on one chip). NVidia
implementations also cache the compiled kernel (I think), which means they
tend to do better.

Also worth checking if your software compiled with optimisations turned on?

**Comment by jake2184** [comment]
So it's acceptable to just leave it with less precision?

The speed was my mistake - it was failing to find a file and exiting, hence the very short execution time, and I missed the error message. Having noticed that the GPU execution is slower as expected.

The #pragma appears to have no effect.

**Comment by m8pple** [comment]
Yes, you can expect the level of inaccuracy you're seeing as a consequence
of non-ideal real numbers.

(Note to others who may be reading this - floating-point errors will be very
small and only grow slowly with the number of calculations. An error of
10% after two steps can't be magicked away by saying "ah, floating-point!".)
