### ISSUE TITLE
cannot find -lOpenCL

### ISSUE THREAD

**Issue by uarif1** [HPCE/hpce-2017-cw3#50]
Hi 
I am using the canned mingw64. When i run the command:

g++ -I include -W -Wall -std=c++11 -O3 -o bin/test_opencl src/test_opencl.cpp src/heat.cpp  -lOpenCL

to test if openCL is working i get:

cannot find -lOpenCL

Do you know how to solve this?

**Comment by guigzzz** [comment]
Use make. Add the following to your makefile:
```
LDFLAGS +=  -Iopencl_sdk/include -Lopencl_sdk/lib/windows/x86_64
LDLIBS += -lOpenCL
```
(make in mingw is called `mingw32-make`)

**Comment by uarif1** [comment]
Thanks, that worked.
