### ISSUE TITLE
Cannot compile project on mac

### ISSUE THREAD

**Issue by abbachinomnso** [HPCE/hpce-2017-cw3#51]
<img width="1280" alt="cannotbuildproj_testopencl" src="https://user-images.githubusercontent.com/20027717/32130144-815ecf26-bb8a-11e7-9fcc-47eab161e095.png">

I get this error message
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

on terminal, make all makes run files for all other three cpp files in bin except the test_openCl.cpp file.
Am i missing any step in the setup that is hindering the project from compiling fully?

**Comment by JayRod12** [comment]
I ran into a similar situation. What I've ended up doing is using Vagrant, which is already configured on the project and pretty much works out of the box.

**Comment by abbachinomnso** [comment]
Thank you. @JayRod12 
I have vagrant up and running now but test_opencl still is not building. 
Am I doing something wrong?
<img width="570" alt="runvagrantbuttestopenclnotbuilding" src="https://user-images.githubusercontent.com/20027717/32134104-98e7bd9e-bbdd-11e7-9224-9a8f6b771362.png">

**Comment by abbachinomnso** [comment]
@JayRod12

**Comment by JayRod12** [comment]
The provided makefile does not build it by default. Either try to build it manually or use cmake. There's a fairly good CMakeLists.txt already setup.

**Comment by JayRod12** [comment]
And that worked for me.
BTW I get notified automatically because I replied previously.

**Comment by abbachinomnso** [comment]
ok. Thank you. I am still lost.
I do not really know what cmake is meant to be doing for me. I think i figured out what vagrant does - to mirror linux unto my machine so i can basically work inn linux from command line. both my normal bash terminal and the bash one all seem to not recognise the ccmake command. I tried compiling the test_opencl.cpp file separately on its own using gcc test_opencl.cpp -o test_opencl -std=c++11 but i get the error that 

test_opencl.cpp:22:10: fatal error: 'CL/cl.hpp' file not found
#include "CL/cl.hpp"
         ^~~~~~~~~~~
1 error generated.

I then try compiling it on its own on vagrant using gcc test_opencl.cpp -o test_opencl -std=c++11
and I get a whole load of **
<img width="1280" alt="from vagrsnt" src="https://user-images.githubusercontent.com/20027717/32134311-b0b86cc0-bbe2-11e7-8fdc-1fb9452683e4.png">

When you say "And that worked for me", what exactly do you mean. like what exactly did you do? did you modify the makefile in the project? did you use the cmake GUI for mac and if so what command did you run afterwards?

**Comment by JayRod12** [comment]
So if you're using vagrant, then install the vm with `vagrant up` then do `vagrant ssh` to connect to the virtual machine. Then from inside the virtual machine, clone the repository.

You might have to install cmake (`sudo apt-get install cmake`), and other tools if you wanna use other tools.

What cmake does is construct a Makefile according to the platform you're on and where your packages are installed.

Then cd to the repo and you can do `cmake .` (to create a new makefile (remove the old one or give it a new name).

At first I had some errors and I had to comment out two lines, as pointed in Issue [#37](https://github.com/HPCE/hpce-2017-cw3/issues/37).

At this point I had a working `bin/test_opencl` binary.
See if these steps work for you.

**Comment by adamsolomou** [comment]
Hey, I used this on terminal and it compiled (with some warnings) 

`g++ -I include -W -Wall -std=c++11 -O3 -I ./opencl_sdk/include/ -o bin/test_opencl src/test_opencl.cpp -o bin/test_opencl -framework OpenCL`

it will generate an executable in the bin folder (you need to create the bin folder first) and then you can execute the program using `bin/test_opencl`

**Comment by louisblin** [comment]
Following up on @adamosSol's solution, it seems [frameworks in OS X](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html) automate the underlying dynamic linking with `-lOpenCL`. So to keep using the original `makefile`, I just changed:
```make
# LDLIBS += -lOpenCL
```
for
```make
LDLIBS += -framework OpenCL
```
and building the test target is now as easy as doing
```bash
make bin/test_opencl
```

**Removing warnings**: most of them are `deprecated-declarations` and `unused-parameter` from the OpenCL library, which can be removed by including the headers in the `makefile` as "[system headers](https://stackoverflow.com/questions/1867065/how-to-suppress-gcc-warnings-from-library-headers)". In the `makefile`, change:
```
CPPFLAGS += -I include
```
for 
```
CPPFLAGS += -isystem include
```
And to remove the last `unused-parameter` from `test_opencl.cpp` you can remove the parameters from the `main` function definition:
```c++
int main(int argc, char *argv[])
```
becomes:
```c++
int main()
```
Doing that allowed me to compile and run all targets without any warning.

**Comment by abbachinomnso** [comment]
@JayRod12  Thank you. I only just saw this now and I already went with @adamosSol solution and that worked for me. also @louisblin you the man... removed all the errors.
Thank you all for your answers. I will now go ahead and close this
