### ISSUE TITLE
AWS GPU Image notes

### ISSUE THREAD

**Issue by BaronKhan** [HPCE/hpce-2017-cw3#52]
I feel there should be more information on how to use the AWS GPU Image provided.

The readme should mention that the image is located in the Amazon AWS Marketplace as a Community AMI, on the N. Virginia region (I defaulted to Ohio and then switched to London, so spent ages trying to find the image; I only found it thanks to this issue: https://github.com/HPCE/hpce-2017-cw3/issues/19).

I think you also have to SSH to a different user account name instead of `ubuntu`, which was the account name used for the standard ubuntu servers (in CW2). I could only ssh using `ssh -A -i ... admin@...`, (I tried using the `root` account but it just tells you to use `admin` instead).

If this is explained in future coursework, then just ignore this (but it doesn't seem to be mentioned in CW4), but it would be great to have a small footnote about this somewhere.

**Comment by m8pple** [comment]
Yes, those are good points - I think I always choose N. Virginia, so hadn't
thought about that aspect. I'll update the readme.

Thanks.
