### ISSUE TITLE
AWS Credits

### ISSUE THREAD

**Issue by louisdeb** [HPCE/hpce-2017-cw3#55]
I set up my AWS account last week, along with AWS Educate. I left it till now to see if it was just a matter of time, but no.. I still haven't received any AWS credits.

In setting up my AWS Educate account, I linked my AWS account id and thought they might add credits using that.

Is there somewhere on the AWS Educate website that I can find a Promo Code for credits? Should it be done automatically?

**Comment by BaronKhan** [comment]
You should get an email from AWS Educate Support saying that your application was approved. Within that email should be a promo code for $100 credits.

**Comment by louisdeb** [comment]
Great, thanks!
