### ISSUE TITLE
Problem Making Isolation Clean

### ISSUE THREAD

**Issue by ghost** [HPCE/hpce-2017-cw3#56]
In the part on making isolation clean, I have defined the following parameters in void kernel_xy

`void kernel_xy(uint32_t x, uint32_t y, uint32_t w, const float *world_state, const uint32_t *world_properties,float *buffer, float inner, float outer ){
	unsigned index=y*w + x;
	
	... // Rest of code
}`

and have called them as follows 

`kernel_xy(x, y, w, &world.state[0], (const uint32_t *)&world.properties[0], &buffer[0],  inner,outer);`

as instructed in the cw.

However, when i try to compile, the following errors keep on showing: 

`g++ -I include -W -Wall -std=c++11 -O3 -o bin/ksy14/step_world_v2_function src/ksy14/step_world_v2_function.cpp src/heat.cpp  -lOpenCL
src/ksy14/step_world_v2_function.cpp: In function ‘void hpce::ksy14::kernel_xy(uint32_t, uint32_t, uint32_t, const float*, const uint32_t*, float*, float, float)’:
src/ksy14/step_world_v2_function.cpp:18:9: error: ‘world’ was not declared in this scope
     if((world.properties[index] & Cell_Fixed) || (world.properties[index] & Cel
         ^
src/ksy14/step_world_v2_function.cpp: At global scope:
src/ksy14/step_world_v2_function.cpp:14:65: warning: unused parameter ‘world_state’ [-Wunused-parameter]
 void kernel_xy(uint32_t x, uint32_t y, uint32_t w, const float *world_state, co
                                                                 ^
src/ksy14/step_world_v2_function.cpp:14:94: warning: unused parameter ‘world_properties’ [-Wunused-parameter]
 , uint32_t y, uint32_t w, const float *world_state, const uint32_t *world_prope
                                                                     ^
makefile:11: recipe for target 'bin/ksy14/step_world_v2_function' failed
make: *** [bin/ksy14/step_world_v2_function] Error 1
`
Not sure why its not detecting world_properties and world_state and its saying that world is not declared because of this.

Could be a basic mistake but wonder if anyone has this same issue or know the problem?

Thanks.

**Comment by ppp2211** [comment]
You haven't changed the way the body of the kernel actually reads the properties - world.properties[index] does not exist within that scope (that's the point of isolating it), you need to rewrite that to use the pointer you pass to it instead.

**Comment by ghost** [comment]
@ppp2211 Thanks for the prompt reply.

Solved it with your solution  :)
