### ISSUE TITLE
V3 alloca not defined

### ISSUE THREAD

**Issue by eddwhite** [HPCE/hpce-2017-cw3#6]
I could not compile v3 once I added the following code:

``` cpp
    #define __CL_ENABLE_EXCEPTIONS
    #include "CL/cl.hpp"
```

I got a lot of errors about alloca, for example:

```
    error: 'alloca' was not declared in this scope
```

To fix this, I just had to change the code to:

``` cpp
    #define __CL_ENABLE_EXCEPTIONS
    #define alloca __builtin_alloca
    #include "CL/cl.hpp
```

Defining alloca in cl.hpp also worked

I'm working on Windows 7 with Cygwin64.

**Comment by wh1114** [comment]
I was able to run it like 
` bin/mingw64-time.exe bin/make_world 100 0.1 | bin/mingw64-time.exe bin/wh1114/step_world_v3_opencl 0.1 10000 | bin/render_world dump`
and add two numbers together
