### ISSUE TITLE
V4, V5 failing tests

### ISSUE THREAD

**Issue by youssefarizk** [HPCE/hpce-2017-cw3#63]
My V4 and V5 are failing the tests. I think that there is a problem with V4, since V5 is essentially based on it. I haven't changed the .cl file, and my host code looks very semantically similar to what is indicated. However, when I run `bin/make_world 10 0.1 | bin/yr914/step_world_v4_double_bufferedNew` and compare it with the output of `bin/make_world 10 0.1 | bin/step_world`, it is different as shown below. 

<img width="790" alt="screen shot 2017-11-01 at 9 25 14 am" src="https://user-images.githubusercontent.com/24788671/32268359-b3d1c6e8-bee6-11e7-980a-a0f6e4039b94.png">
<img width="795" alt="screen shot 2017-11-01 at 9 25 35 am" src="https://user-images.githubusercontent.com/24788671/32268360-b3ee8a6c-bee6-11e7-8e18-7a400574d14e.png">

As I vary the input parameters to the step_world functions they become more and more similar, baring the slight differences that were mentioned in other issues.

**Comment by youssefarizk** [comment]
Fixed - Issue with which buffers I was changing

**Comment by bnt0** [comment]
Hi @youssefarizk, I'm having the exact same issue. Could you tell me where exactly your mistake was?

**Comment by bnt0** [comment]
nvm, I fixed it too. I was copying from buffBuffer instead of buffState

**Comment by DhruvArora96** [comment]
Hi guys, also had this issue. What buffer changed fixed it for you?

**Comment by ia2314** [comment]
@youssefarizk @bnt0 Same exact issue in v4, does anyone have any advice?
