### ISSUE TITLE
No speedup for Part 4 compared to Part 3

### ISSUE THREAD

**Issue by sclimpro** [HPCE/hpce-2017-cw3#64]
I have managed to compile and run code for Part 3 and Part 4 on AWS t2.micro using the HPCE-2017-GPU-Image.

According to the coursework guide, 'Depending on your platform, you may now start to see a reasonable speed-up over software (though maybe still not over TBB - depends a lot on the hardware).'

Unfortunately, I'm observing similar execution times for both implementations:
bin/make_world 1000 0.1 1 > /tmp/world.bin  # Save binary world to temp file
time (cat /tmp/world.bin | bin/step_world 0.001 1  1 > /dev/null) : **0m0.022s**
time (cat /tmp/world.bin | bin/$USER/step_world_v3_opencl 0.001 1  1 > /dev/null) **0m0.102s**
time (cat /tmp/world.bin | bin/$USER/step_world_v4_double_buffered 0.001 1  1 > /dev/null) **0m0.100s**

Can anyone confirm these observations?
Thanks.

**Comment by m8pple** [comment]
The difference there is ~0.002s, so you might want to consider the question of timer
resolution and accuracy mentioned in the last lecture. Remember that the process has
to be loaded, and OpenCL initialised - how much cost is involved in that, out of the 0.1s runtime?

Also, how much work are you asking your system to do? If you are stepping by 1 time epoch,
how much of that time is involved in copying backwards and forwards?

The difference is pretty small on the AWS hardware, but it is consistent, as you consider the
size of the problem you are asking it to solve (in _time_, as well as space).
