### ISSUE TITLE
Typo for v5 directory.

### ISSUE THREAD

**Issue by sclimpro** [HPCE/hpce-2017-cw3#65]
Typo in Optimising global to GPU memory accesses (v5): Kernel Code.

Kernel code

Create a new kernel called **src**/src/your_login/step_world_v5_packed_properties.cl based on the v4 kernel.

I believe the src was mistakenly included twice.

**Comment by m8pple** [comment]
Oops, yes. Not sure how long that has been sitting there.

Thanks, I'll correct it.
