### ISSUE TITLE
kernel cannot be vectorized 

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw3#70]
Hi,

On running my executable in succession I keep getting an `clEnqueueWriteBuffer `Exception on random runs. On catching the exception and printing the error, it says **kernel cannot be vectorized.**
(Even though this happens, the version passes the automated tests in the log folder ) 

My question is, is it possible to get this exception on running the same executable in quick successions ? Could this be something to do with inability of GPU to execute kernels in quick succession ?

Thanks!

**Comment by m8pple** [comment]
Hrmm, I don't think I have ever seen that error before.

What platform/provider/GPU/OS are you using?

My initial suspicion is that it would be a software provider which is trying to
vectorise to use SSE/AVX, but that wouldn't fit with the symptom of repeated
executions causing the errors.

**Comment by malharjajoo** [comment]
I am using  - 
GPU = Intel HD Graphics
OS = Ubuntu 16.04
