### ISSUE TITLE
v5 misleading snippet?

### ISSUE THREAD

**Issue by janscholten** [HPCE/hpce-2017-cw3#73]
In the last bits (sorry for the pun) of the readme.md, it is advised to pack the properties as shown in the following pseudo-code:
```
packed(x,y) = world.properties(x,y)
if cell(x,y) is normal:
    if packed(x,y-1):
        packed(x,y) = packed(x,y) + 4
    if packed(x,y+1):
        packed(x,y) = packed(x,y) + 8
    # Handle left and right cases
```

However, as the whole `packed()` vector is initialized as zero, incrementally copying from `world_properties` does not support looking ahead for properties of the below and right cells as far as I understand. I suggest copying the whole vector first, or looking up in the original `world_properties` vector. It would boil down to something like this:
```
packed(x,y) = world.properties(x,y)
if packed(x,y) is normal:
    if world.properties(x,y-1):
        packed(x,y) = packed(x,y) + 4
    if world.properties(x,y+1):
        packed(x,y) = packed(x,y) + 8
    # Handle left and right cases
```

**Comment by m8pple** [comment]
Puns are the highest form of comedy, they need no excuse.

Yes, you're right - the pseudo-code wouldn't work if implemented
as currently given.

I'll update it to:
```
packed(x,y) = world.properties(x,y)
if world.properties(x,y) is normal:
    if world.properties(x,y-1) is insulator:
        packed(x,y) = packed(x,y) + 4
    if world.properties(x,y+1) is insulator:
        packed(x,y) = packed(x,y) + 8
    # Handle left and right cases
```

Thanks.
