### ISSUE TITLE
CL/opencl.h: No such file or directory error when building test_opencl on DoC machine

### ISSUE THREAD

**Issue by rizmaster25** [HPCE/hpce-2017-cw3#74]
When trying to build the `test_opencl.cpp` file on a matrix DoC machine, I get the following error

`include/CL/cl.hpp:161:23: fatal error: CL/opencl.h: No such file or directory`

Anyone know if that means that the necessary drivers are not installed on the machine? I find it weird because it keeps happening on every matrix machine I ssh into. Has anyone encounter this same issue?

**Comment by m8pple** [comment]
Have you tried looking at #44 ?

The command embedded which appears as part of the makefile execution is:
```
g++ -I include -W -Wall -std=c++11 -O3 -I ./opencl_sdk/include/ -o bin/test_opencl src/test_opencl.cpp src/heat.cpp -L /usr/lib/x86_64-linux-gnu -L . -l OpenCL
```
That worked for me on a normal matrix machine (I have no special privileges on the machines).

Note the dance needed to link to `libOpenCL.so` though.

**Comment by rizmaster25** [comment]
Yes, I've seen it now, but for some reason when I initially executed `make bin/test_opencl`, the second `-I ./opencl_sdk/include/` was missing from the command in the makefile. I guess that if I update the makefile it should compile now with the make command
