### ISSUE TITLE
 Choosing a device for submission

### ISSUE THREAD

**Issue by Afraz496** [HPCE/hpce-2017-cw3#75]
Hi, i’ve finally understood why i’ve been failing the tests, in Macs, the GPU is listed as device 1 is why I chose the default as 1, i’ve submitted that on my github. The tests however rely on the default device 0, so in essence a device is never picked and it doesn’t run on the GPU. I’ll change the default to device 0. Will there be one more run of the logs? And is it necessary to keep 0 as the default for the final submission?

**Comment by m8pple** [comment]
There's a test running now, and I'll probably do another one after the lecture (as this one is fairly
fast).

In the absence of extra information or a specific selection, one usually tries to pick the
device that looks "fastest", for example by using [clGetDeviceInfo.html](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clGetDeviceInfo.html),
and selecting based on `CL_DEVICE_TYPE`.

For anything where the user really cares about performance, they would usually
choose the device manually, using a setting or environment variable.

In our case, we know the exact machine and OpenCL provider in which the code
is going to be run "for real" (including the order in which they are listed), so the
default of 0 would select the best device (regardless of what it does on the Mac).
So the AWS instance is "production", while the Mac is "test" or "dev" - defaults should
usually favour the production environment, and any deviations in the test environment
(and especially dev) environments should be explicit changes away from the
default.
