### ISSUE TITLE
opencl.dll not found in canned environment

### ISSUE THREAD

**Issue by JB515** [HPCE/hpce-2017-cw3#76]
I am trying to run test_opencl in the provided mingw environment. I managed to get it building successfully but it won't run because OpenCL.dll can't be found. I have all my NVIDIA drivers up to date and can find OpenCL32.dll and OpenCL64.dll in my windows install, but not OpenCL.dll.

Does anyone know where to get this and where to put it?

**Comment by benfwalker** [comment]
It might be a bit late, but have you tried just changing the name of one of those to OpenCL.dll? (probably the 64 one)

**Comment by JB515** [comment]
Update: a wider search of my system has located some version of OpenCL.dll, and pasting it in various places around my cw3 directory allows opencl programs to at least run, but test_opencl crashes so I'm guessing I have the the wrong file.
