### ISSUE TITLE
v4 is 1 time step behind.

### ISSUE THREAD

**Issue by DhruvArora96** [HPCE/hpce-2017-cw3#77]
![v4_code](https://user-images.githubusercontent.com/25771571/32353559-c9a21990-c01d-11e7-91d8-925df05744dc.png)
For v4, my output is one timestep behind the reference. 
Me doing 
bin/make_world 10 0.1 | bin/da1414/step_world_v4_double_buffered 0.1 2
Gives the same output as 
bin/make_world 10 0.1 | bin/step_world 0.1 1
I have attached my code if someone can see the mistake.

**Comment by t-sujone** [comment]
Did you work this out? Mine is actually doing the same

**Comment by DhruvArora96** [comment]
@t-sujone  Yes, I did solve it. At the end of the for loop, instead of reading from buffBuffer, read from buffState.  This is because once you swap buffState with buffBuffer, buffBuffer contains the original value of the world, which you then read into world.state, which is wrong.
