### ISSUE TITLE
Auto test for CW3 doesn't allow for TBB?

### ISSUE THREAD

**Issue by sclimpro** [HPCE/hpce-2017-cw3#78]
It seems like the auto test run environment doesn't support TBB? It is possible to complete CW3 without parallel_for, but I don't see why it the test environment doesn't support it?

Below is the log for build_v5_packed_properties.log:

src/scl214/step_world_v5_packed_properties.cpp:16:30: fatal error: tbb/parallel_for.h: No such file or directory
 #include "tbb/parallel_for.h"
                              ^
compilation terminated.

**Comment by janscholten** [comment]
I'm having the same issue

**Comment by m8pple** [comment]
Oh, that's not intentional - as far as I remembered it had libtbb-dev in the provisioning
script, but apparently not, as the package isn't installed.

I've put it in manually, so feel free to use it if you wish.

**Comment by tszyszko** [comment]
The most recent tests still fail when linking TBB: 
"/usr/include/tbb/task.h:969: undefined reference to `tbb::internal:"

**Comment by m8pple** [comment]
Ah - I forgot that you don't have control of the build command for this one, so the
last two runs had TBB in the environment, but the build command did not
have the `-ltbb`. 

Afraid I was a bit led astray by the reference to "environment", as I forgot that in
this case it needs to be interpreted both as the build environment and the build command.
For the final assessment, the `-ltbb` is added as well.
