### ISSUE TITLE
Autotester seems to be checking previous commits

### ISSUE THREAD

**Issue by ghost** [HPCE/hpce-2017-cw3#79]
I notice the autotester seems to be checking previous commits 

For example in my latest auto test script it says:
 Auto test 2017-11-02 --1842

However , upon looking at the logs, it checked a commit hash which was done on 
2017-11-01 -- 2216

Funny thing is the latest commit in my cw3 repository(before latest test) is on :
2017-11-02 --1834

As it is testing an older commit , some  tests failed  -  Am wondering why it does not test the latest file.

Wonder if this is an  issue or did I make a mistake / did not do something properly. 

Thanks.

**Comment by sighellan** [comment]
There is a time gap between when he pulls the code and pushes back the results. 
See [here](https://github.com/HPCE/hpce-2017-cw2/issues/67).

**Comment by ghost** [comment]
@sighellan  ah okay thanks!
