### ISSUE TITLE
OpenCL on MinGW Windows 10

### ISSUE THREAD

**Issue by samuraisoldier** [HPCE/hpce-2017-cw3#86]
I've been trying to run make bin/test_openCL from MinGW but I get the following error:

mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lOpenCL
collect2.exe: error: ld returned 1 exit status

Has anyone been able to make it work? I'm using a Windows 10 laptop, with Intel i7 and an AMD Radeon. 

I've tried installing the intel OpenCL SDK, tried adding OpenCL.dll file to different folders, tried to find an amd openCL SDK, and now I'm trying to install Cygwin.

**Comment by mantzouj** [comment]
Not sure if this helps, but I had similar issues
I got rid of that error when I added these to the makefile:
LDFLAGS += -Iopencl_sdk/include -Lopencl_sdk/lib/windows/x86_64
LDLIBS += -lOpenCL

Later I got other issues, which I solved by doing this:
To get test_opencl to compile (I kept getting the "underfined reference to ..." errors), I had to copy the OpenCL.lib from the OpenCl folder in my C:\Intel directory to the project directory (opencl_sdk\lib\windows\x86_64). I also didn't need the new files that were committed to opencl_sdk\include. This was all after I installed the Intel SDK for OpenCl

**Comment by samuraisoldier** [comment]
Thank you! The second part of your answer got mine working
