### ISSUE TITLE
Cannot SSH into AWS 

### ISSUE THREAD

**Issue by szetyng** [HPCE/hpce-2017-cw3#88]
I've created and launched an instance from the HPCE-2018 image and generated an SSH key-pair. I've changed the permission so that only I can access it, but when I try to run `ssh -A -i [your-key] admin@[server-ip-address]`, I keep getting `Permission denied (publickey)`.

**Comment by adityarajagopal** [comment]
Sometimes the admin@ is not meant to be admin bur root or centos or something like that. So might be worth checking if that's the case. Also, when you say you changed the permission so that only you can access it, did you run "chmod 400" on the .pem file?

**Comment by szetyng** [comment]
Yes, I ran chmod 400. I changed it to `ssh -A -i [your-key] ubuntu@[server-ip-address]` and it works now, thanks :)
