### ISSUE TITLE
Problem on opencl installation for nvidia on WSL

### ISSUE THREAD

**Issue by DominicCYK** [HPCE/hpce-2017-cw3#9]
As stated in the title, i have installed 

> nvidia-340, nvidia-modprobe, nvidia-opencv-dev 
> Then "test_opencl.cpp" is able to be compiled. However, an error appeared 
> 
> modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.4.0+/modules.dep.bin'
> modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.4.0+/modules.dep.bin'
> modprobe: ERROR: ../libkmod/libkmod-module.c:809 kmod_module_insert_module() could not find module by name='nvidia_340'
> modprobe: ERROR: could not insert 'nvidia_340': Function not implemented
> Exception : clGetPlatformIDs

when  running the compiled code. I have tried "depmod" command to map the dependency. However, another error appeared:

>  depmod: ERROR: could not open directory /lib/modules/3.4.0+: No such file or directory
> depmod: FATAL: could not search modules: No such file or directory

Can someone please help?

**Comment by hamish-milne** [comment]
WSL is still pretty basic. It doesn't have much in the way of hardware/driver support. I'd suggest using CLion in native Windows - it seems to work fine, with a small patch which I'll be adding as an issue in a moment.

**Comment by DominicCYK** [comment]
Thanks , Clion works perfectly with Cmake

**Comment by m8pple** [comment]
Sorry, the WSL experience is not as complete as I thought. My tests
over the summer suggested it worked, but it looks I was actually
doing it in a MinGW shell. I need to give all my different shells
distinct colours, as I keep accidentally ending up in the wrong one.
